apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure
  labels:
    app: medicure
  spec:
    replicas: 3
    selector:
     matchLabels:
     app: medicure
  template:
    metadata:
    labels:
    app: medicure
  spec:
    containers:
    name: medicure
    image: gpavankumarreddy/dilipreddy:medicure
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  selector:
  app: medicure
  type: NodePort
  ports:
  - protocol: TCP
  port: 80
  targetPort: 8080
  nodePort: 30010
